name = "AdaptiveCrossApproximation"
uuid = "ef3ffb92-1c7b-43b8-a0d7-a7e2ce4fd1e5"
version = "0.1.0"
authors = ["JoshuaTetzner <joshua.tetzner@uni-rostock.de>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
H2Trees = "9db26ae3-82ff-4374-85e9-9ed87405fd16"

[extensions]
ACAH2Trees = ["H2Trees"]

[compat]
H2Trees = "0.1"
Polynomials = "4.1.0"
StaticArrays = "1.9.13"
julia = "1.10, 1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
H2Trees = "9db26ae3-82ff-4374-85e9-9ed87405fd16"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Aqua", "JET", "JuliaFormatter", "Test", "TestItemRunner", "TestItems", "Random", "H2Trees"]
